package org.snakeskin.component

import org.snakeskin.component.provider.IDigitalSignalProvider
import org.snakeskin.component.provider.IInvertableInputProvider

interface IDigitalSensorComponent: IDigitalSignalProvider, IInvertableInputProvider